id: I0B70EB14
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:28:23.293447
last_modified: 2023-01-04 11:28:23.293462
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  F449:
    title: Brief Biography of Tāranātha
    base_file: F449.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
